version: "3"
services:
  goserver:
    build: .
    ports:
      - 8080:8080
      - 8081:8081
    volumes:
      - .:/go/src/app/
    env_file:
      - ./secret.env
        #    command: >
        #      bash -c "cd /go/main; go run main.go"
