version: "3"
services:
  goserver:
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/go/src/app/
    env_file:
      - ./secret.env
        #    command: >
        #      bash -c "cd /go/main; go run main.go"
  dbweb:
    build: './dbweb'
    env_file:
      - ./dbweb/dbwebsecrets.env
    ports:
      - "5432:5432"
