version: "3"

services:
  nginx:
    build: "./nginx"
    image: ${NGINX_IMAGE}
    ports:
      - "80:80"
  dbweb:
    build: './vigyaa-dev/dbweb'
    image: ${DB_WEB_IMAGE}
    env_file:
      - ./vigyaa-dev/dbweb/dbwebsecrets.env
    ports:
      - "5432:5432"
  memcached-web:
    build: "./vigyaa-dev/memcachedweb"
    image: ${MEMCACHED_WEB_IMAGE}
    env_file:
      - ./vigyaa-dev/memcachedweb/memcachedweb-variables.env
    ports:
      - "11211:11211"
  web:
    build: ./vigyaa-dev
    image: ${WEB_IMAGE}
    env_file:
      - web-variables.env
    command: >
      bash -c "python manage.py makemigrations && python manage.py migrate --fake && gunicorn vigyaa.wsgi -b 0.0.0.0:8000 -w 3 --timeout 100000"
    ports:
      - "8000:8000"
